import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Apenia A.I. Bank",
  description: "Generated by create next app",
  icons: {
    icon: ["/images/favicon_io/favicon.ico"],
    manifest: "/images/favicon_io/site.webmanifest",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
